name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests wakatime
      - name: Fetch WakaTime data
        run: |
          curl -H "Authorization: Bearer ${{ secrets.WAKATIME_API_KEY }}" \
            "https://wakatime.com/api/v1/users/current/stats/last_7_days" -o wakatime_data.json
          cat wakatime_data.json
      - name: Update README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: False

